blackduck:
  url: 'url'
  trust.cert: true
  username: 'username'
  password: 'Password'
  api.token: ''
  offline.mode: true
detect:
  cleanup: false
  project.name: 'project'
  project.version.name: '1.0'
  blackduck.signature.scanner.snippet.matching: 'FULL_SNIPPET_MATCHING'
  blackduck.signature.scanner.individual.file.matching: 'ALL'
  blackduck.signature.scanner.exclusion.name.patterns: ''
  tools: 'BINARY_SCAN' #required for binary scan
  binary.scan.file.path: '' #required for binary scan
logging:
  level.com.synopsys.integration: 'DEBUG'
