blackduck:
  url: 'url'
  trust.cert: true
  username: 'username'
  password: 'Password'
  api.token: ''
  offline.mode: true
detect:
  cleanup: false
  project.name: 'project'
  project.version.name: '1.0'
  code.location.name: 'name'
  blackduck.signature.scanner.snippet.matching: 'FULL_SNIPPET_MATCHING'
  blackduck.signature.scanner.individual.file.matching: 'ALL'
  blackduck.signature.scanner.exclusion.name.patterns: ''
  tools: 'BINARY_SCAN' #required for binary scan
  tools.excluded: 'DETECTOR'
  binary.scan.file.path: '' #required for binary scan
  blackduck.signature.scanner.upload.source.mode: true
  blackduck.proxy.host: hostname
  blackduck.proxy.port: port
  docker.tar: 'docker.tar'
  docker.passthrough.service.timeout: 240000
  detect.docker.image: imagename
  detector.search.exclusion: 'Director1,Directory2'
  impact.analysis.enabled: true
  
logging:
  level.com.synopsys.integration: 'DEBUG'
 
 
