blackduck:
  url: 'url'
  trust.cert: true
  username: 'username'
  password: 'Password'
detect:
  project.name: 'project'
  blackduck.signature.scanner.snippet.matching: 'FULL_SNIPPET_MATCHING'
  blackduck.signature.scanner.individual.file.matching: 'ALL'
  detect.blackduck.signature.scanner.exclusion.name.patterns
